[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "made-in-cameroon-market"
path = "crates/api/src/main.rs"


[workspace]
members = [
    "crates/api",
    "crates/cache",
    "crates/sync",
    "crates/metrics",
]