name: Backend Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-${{ hashFiles('backend/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

  backend_checks:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust stable
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env

      - name: Cargo Format Check
        working-directory: backend
        run: cargo fmt -- --check

      - name: Clippy Linting
        working-directory: backend
        run: cargo clippy -- -D warnings

      - name: Cargo Tests
        working-directory: backend
        run: cargo test --workspace -- --nocapture

      - name: Cargo Build (Release)
        working-directory: backend
        run: cargo build --release

      - name: Upload Backend Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-release
          path: backend/target/release/made-in-cameroon-market
