name: CI Pipeline

on:
  merge_group:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      
      - name: Format Check
        working-directory: backend
        run: cargo fmt --all --check

  cargo-build:
    env:
      RUSTFLAGS: -D warnings
    name: Cargo Build
    runs-on: ubuntu-latest
    needs: format-check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cargo Build
        working-directory: backend
        run: cargo build --all-features --all-targets

  cargo-clippy:
    name: Cargo Clippy
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      
      - name: Cargo Clippy
        working-directory: backend
        run: cargo clippy --all-features --all-targets

  cargo-test:
    name: Cargo Test
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run cargo nextest
        working-directory: backend
        run: cargo nextest run --all-features --all-targets

  cargo-doc-test:
    name: Documentation Test
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run Documentation Tests
        working-directory: backend
        run: cargo test --doc --all-features

  unused-deps:
    name: Check Unused Dependencies
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-machete
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-machete

      - name: Run cargo machete
        working-directory: backend
        run: cargo machete --with-metadata

  cargo-audit:
    name: Check for Vulnerabilities
    runs-on: ubuntu-latest
    needs: cargo-build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - name: Run cargo audit
        working-directory: backend
        run: cargo audit
